//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMASD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDNOMINA2020Entities : DbContext
    {
        public BDNOMINA2020Entities()
            : base("name=BDNOMINA2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<nominaEmpleado> nominaEmpleadoes { get; set; }
        public virtual DbSet<tabulador> tabuladors { get; set; }
        public virtual DbSet<nomina> nominas { get; set; }
    }
}
