//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMASD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tabulador
    {
        public int tabuladorId { get; set; }
        [DisplayName("Sueldo ($)")]
        public decimal sueldo { get; set; }
        [DisplayName("Prima Vacacional (%)")]
        public decimal primaVacacional { get; set; }
        [DisplayName("Días de aguinaldo")]
        public int aguinaldo { get; set; }
        [DisplayName("Vales de despensa ($)")]
        public Nullable<decimal> vales { get; set; }
        [DisplayName("Días de Vacaciones")]
        public int vacaciones { get; set; }
        public int numEmpleado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
